new cli argument. fix download
pspeter/statement-dl pull request #5
Opened 2022-12-05 00:57 UTC by Krensi

Hi. I fixed the issue with the index and added an CLI option to store the PDFs in separate sub directories.
However, the download does not work anymore, because Flatex might have changed a javascript element.

This does not work anymore: 
```
onfinished = """
    DownloadDocumentBrowserBehaviorsClick.finished = function(a, b) {
       console.log(a);
       window.pdf_download_url = a;
    };
"""
```

DownloadDocumentBrowserBehaviorsClick cannot be found.

Unfortunately, I cannot figure out how to fix this problem.

2022-12-06 22:27 UTC, pspeter requested changes
Hey @Krensi! Thanks a lot for your contribution :)
I'm afraid I won't be able to look into the second issue you found this year, but I will gladly accept your PR after one small change with the argument ordering.

2022-12-06 22:27 UTC, pspeter commented on src/statement_dl/flatex.py
>      keep_filenames: bool,
```suggestion
    keep_filenames: bool,
    sub_dirs: bool,
```

2022-12-06 22:59 UTC, Krensi commented on src/statement_dl/flatex.py
>      keep_filenames: bool,
Cool thanks :-) 
Do you have a Suggestion where I coul start looking? I am not sure where the HTML element (the button) might have been. But i guess it was within the document popup window? 

Cheers from Graz :-)

2022-12-07 19:06 UTC, pspeter commented on src/statement_dl/flatex.py
>      keep_filenames: bool,
To be honest, I don't remember the exact details on how this part of the code worked. The "button" that usually opens a new tab and starts the download is actually an `onclick` event on the rows of the table that calls some JavaScript, you can see it using the developer tools of your browser, e.g.:

![image](https://user-images.githubusercontent.com/13824347/206271238-a35eb5ad-d768-4d10-a617-06ab8737dd36.png)

Looks like they renamed some stuff, namely `documentArchiveListTable` to `documentArchiveListForm_documentArchiveListTable` and `selectedRowIdx` to `data-value-selectedrowidx`, so maybe that just needs to be changed here:

https://github.com/pspeter/statement-dl/blob/13e74c47b26a5cc4a6edd9f8e6f0d5fbcc028176/src/statement_dl/flatex.py#L23-L29

That might fix the `onfinished` event as well. I can't test things at the moment, but be my guest! 😃 Cheers from Vienna 👋 !

2022-12-09 14:30 UTC, Krensi commented on src/statement_dl/flatex.py
>      keep_filenames: bool,
Unfortunately, this did not fix the problem. The `onfinished` is still broken and I cannot figure out how to extract the URL from the popup window. But the thing is my javascript skills are rather limited. :-D

Anyway, thanks for your reply and help. :-)

2023-01-17 20:27 UTC, Krensi commented
Hi! 

I fixed the issue with the unknown element. The expression`DownloadDocumentBrowserBehaviorsClick.finished` was changed to `DocumentViewer.display`.

Unfortunately, the insertion of the date throws an error now.
I have played around with selenium quite a bit. To sum up -> It is a pain in the ass.

Recently we discovered an alternative based on plain http requests. This was also not working instantly, but after some small changes it works really well. 

Checkout our pull request -> https://github.com/mitsuhiko/flatex-pdf-download/pull/4

2023-01-20 20:52 UTC, pspeter commented
Wow! Thanks for your great work. I just tried your fix and it works flawlessly, even the date insertion. Not sure why it would bug out for you.

Thanks for the tip with the other project, definitely simpler if you don't have to deal with the actual html. I agree that selenium can be a pain, but I was worried about getting blocked by flatex, which is why I chose this approach.
Congrats on fixing two flatex downloaders within a week ;)

2023-01-20 20:53 UTC, pspeter approved these changes

2023-01-20 20:55 UTC, merged